import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8080/api';
const views = ['overview', 'day', 'learning', 'money', 'people'];

function Pill({ children, tone = 'quiet' }) { return <span className={`status-pill ${tone}`}>{children}</span>; }
function Tag({ children, tone = '' }) { return <span className={`tag ${tone}`}>{children}</span>; }

function Sidebar({ view, setView }) {
  const items = [['overview', '⌂', 'Overview'], ['day', '◷', 'My day'], ['learning', '◇', 'Learning'], ['money', '⌁', 'Money'], ['people', '♧', 'People & lending']];
  return <aside className="sidebar">
    <div className="brand"><div className="brand-mark">✦</div><div><strong>rajesh</strong><span>personal workspace</span></div></div>
    <div className="profile"><div className="avatar">R</div><div><strong>Rajesh</strong><span>Builder mode</span></div><button className="icon-btn">•••</button></div>
    <nav className="nav" aria-label="Primary navigation">{items.map(([id, icon, label]) => <button key={id} className={`nav-item ${view === id ? 'active' : ''}`} onClick={() => setView(id)}><span>{icon}</span>{label}{id === 'learning' && <em>3</em>}{id === 'people' && <em>2</em>}</button>)}</nav>
    <div className="sidebar-bottom"><div className="focus-card"><span className="eyebrow">TODAY'S INTENTION</span><p>Make progress visible.</p><small>4 of 6 blocks planned</small><div className="mini-progress"><i style={{ width: '68%' }} /></div></div><button className="nav-item muted"><span>⚙</span> Settings</button></div>
  </aside>;
}

function Header({ setView }) { return <header className="topbar"><div><span className="eyebrow">THURSDAY, 02 OCTOBER 2026</span><h1>Good morning, Rajesh <span className="sun">✳</span></h1></div><div className="top-actions"><button className="date-btn">Today <span>⌄</span></button><button className="primary-btn" onClick={() => setView('day')}>＋ Add entry</button></div></header>; }

function Overview({ setView, dashboard }) {
  const { stats, timeline, courses, loans } = dashboard;
  return <>
    <section className="hero-grid"><div className="today-card card"><div className="card-heading"><div><span className="eyebrow lime">DAILY PULSE</span><h2>One day at a time.</h2></div><Pill tone="good">On track</Pill></div><p className="hero-copy">You’ve protected <strong>2h 30m</strong> for deep work today. Keep the promise to future you.</p><div className="metric-row"><div><strong>{stats.focusedTime}</strong><span>focused time</span></div><div><strong>{stats.habits}</strong><span>habits complete</span></div><div><strong>{stats.next30Days}</strong><span>next 30 days</span></div></div><div className="today-foot"><span>Day score</span><strong>{stats.dayScore}%</strong><div className="progress"><i style={{ width: `${stats.dayScore}%` }} /></div></div></div><div className="quote-card card"><span className="eyebrow coral">NORTHSTAR NOTE</span><p>“Small systems beat big intentions.”</p><div className="quote-line" /><span className="quote-author">— James Clear</span></div></section>
    <section className="dashboard-grid"><div className="card schedule-card"><div className="card-heading"><div><span className="eyebrow">DAY PLAN</span><h3>Thursday timeline</h3></div><button className="text-btn" onClick={() => setView('day')}>View full day →</button></div><div className="timeline">{timeline.map((item, i) => <div className={`time-row ${item.status === 'done' ? 'done' : ''} ${item.status === 'active' ? 'active-row' : ''}`} key={item.time}><span className="time">{item.time}</span><i /><div><strong>{item.title}</strong><small>{item.subtitle}</small></div>{item.status === 'done' ? <b>✓</b> : item.status === 'active' ? <span className="live-dot">live</span> : <Tag tone={item.type === 'course' ? 'blue' : 'violet'}>{item.type}</Tag>}</div>)}</div></div>
      <LearningCard courses={courses} setView={setView} /><MoneyCard setView={setView} /><LendingCard loans={loans} setView={setView} /></section>
  </>;
}

function LearningCard({ courses, setView }) { return <div className="card focus-card-main"><div className="card-heading"><div><span className="eyebrow">LEARNING STREAK</span><h3>Career capital</h3></div><button className="icon-btn">•••</button></div><div className="learning-main"><div className="ring"><span>12</span><small>days</small></div><div><strong>Keep the chain alive</strong><p>3 sessions this week</p><div className="week-dots"><i className="filled" /><i className="filled" /><i className="filled" /><i className="filled" /><i /><i /><i /></div><small className="muted-text">Mon – Sun</small></div></div><div className="course-list">{courses.map(course => <div key={course.name}><span className={`course-dot ${course.color}`} /><span>{course.name}</span><b>{course.progress}%</b></div>)}</div></div>; }
function MoneyCard({ setView }) { return <div className="card money-card"><div className="card-heading"><div><span className="eyebrow">MONEY RADAR</span><h3>Coming up</h3></div><button className="text-btn" onClick={() => setView('money')}>Manage →</button></div><div className="money-total"><strong>₹18,400</strong><span>due in the next 30 days</span></div>{[['Auto pays', '₹9,200', '72%'], ['SIPs', '₹6,000', '48%'], ['Subscriptions', '₹3,200', '26%']].map(([label, amount, width], i) => <div className="money-bars" key={label}><div><span>{label}</span><b>{amount}</b><i><em className={i === 1 ? 'orange' : i === 2 ? 'pink' : ''} style={{ width }} /></i></div></div>)}</div>; }
function LendingCard({ loans, setView }) { return <div className="card lending-card"><div className="card-heading"><div><span className="eyebrow">OPEN LOOPS</span><h3>People & lending</h3></div><span className="count-badge">{loans.length}</span></div>{loans.map(loan => <div className="loan" key={loan.name}><div className={`person-avatar ${loan.color}`}>{loan.initials}</div><div><strong>{loan.name}</strong><small>{loan.amount} · due {loan.dueDate}</small></div><Pill tone={loan.tone}>{loan.status}</Pill></div>)}<button className="outline-btn" onClick={() => setView('people')}>＋ Log a repayment</button></div>; }

function DetailView({ view, dashboard, setView }) {
  if (view === 'day') return <section className="detail-view"><SectionHeading eyebrow="MY DAY" title="Time is a budget." action="＋ Add time block" /><div className="day-layout"><div className="card day-table"><div className="day-table-head"><span>TIME</span><span>ACTIVITY</span><span>TYPE</span><span>STATUS</span></div>{dashboard.timeline.map(item => <div className="day-table-row" key={item.time}><span>{item.time}</span><strong>{item.title}</strong><Tag tone={item.type === 'work' ? 'blue' : 'violet'}>{item.type}</Tag><b className={item.status === 'done' ? 'complete' : item.status === 'active' ? 'current' : ''}>{item.status === 'done' ? 'Completed' : item.status === 'active' ? 'In progress' : 'Planned'}</b></div>)}</div><div className="card week-card"><span className="eyebrow">THIS WEEK</span><h3>Office / study balance</h3><div className="chart">{[54, 72, 46, 82, 40, 24, 18].map((height, i) => <div className={i === 3 ? 'today-bar' : ''} style={{ height: `${height}%` }} key={i}><span>{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][i]}</span></div>)}</div><div className="legend"><span><i className="work-dot" /> work</span><span><i className="study-dot" /> study</span></div></div></div></section>;
  if (view === 'learning') return <section className="detail-view"><SectionHeading eyebrow="LEARNING HUB" title="Build durable skills." action="＋ Add course" /><div className="learning-grid">{dashboard.courses.map((course, i) => <div className="card skill-card" key={course.name}><div className="skill-top"><span className={`skill-icon ${i === 0 ? 'violet-bg' : i === 1 ? 'blue-bg' : 'orange-bg'}`}>{['⌘', '◎', '▱'][i]}</span><Tag tone={i === 0 ? 'violet' : i === 1 ? 'blue' : 'orange'}>{i === 0 ? 'interview prep' : 'course'}</Tag></div><h3>{course.name}</h3><p>{course.subtitle}</p><div className="progress-label"><span>{course.progress}% complete</span><b>{course.completed} / {course.total}</b></div><div className="progress"><i className={`${i === 0 ? 'violet-fill' : i === 1 ? 'blue-fill' : 'orange-fill'}`} style={{ width: `${course.progress}%` }} /></div><button className="primary-btn small">{i === 0 ? 'Continue practice' : 'Resume course'}</button></div>)}</div></section>;
  if (view === 'money') return <section className="detail-view"><SectionHeading eyebrow="MONEY HUB" title="Know where it goes." action="＋ Add transaction" /><div className="finance-grid"><div className="card net-card"><span className="eyebrow">MONTHLY COMMITMENTS</span><div className="big-number">₹18,400</div><p>scheduled across SIPs, auto pays and subscriptions</p><div className="finance-breakdown"><span>Investments <b>₹6,000</b></span><span>Bills & auto pays <b>₹9,200</b></span><span>Subscriptions <b>₹3,200</b></span></div></div><div className="card finance-table"><div className="finance-row head"><span>ITEM</span><span>NEXT DATE</span><span>AMOUNT</span><span>STATUS</span></div>{dashboard.finances.map(item => <div className="finance-row" key={item.name}><strong>{item.name}</strong><span>{item.date}</span><b>{item.amount}</b><Pill tone={item.tone}>{item.status}</Pill></div>)}</div></div></section>;
  return <section className="detail-view"><SectionHeading eyebrow="PEOPLE & LENDING" title="Close the loops kindly." action="＋ Add person" /><div className="people-grid">{dashboard.loans.map(loan => <div className="card person-card" key={loan.name}><div className="person-card-top"><div className={`person-avatar ${loan.color} large`}>{loan.initials}</div><Pill tone={loan.tone}>{loan.status}</Pill></div><h3>{loan.name}</h3><p>{loan.note}</p><div className="loan-amount"><span>Outstanding</span><strong>{loan.amount}</strong></div><button className="outline-btn full">{loan.tone === 'warn' ? 'Send a gentle reminder' : 'Mark as repaid'}</button></div>)}<div className="card note-card"><span className="eyebrow">A GOOD DEFAULT</span><h3>Make lending explicit.</h3><p>Record the amount, a due date, and the next kind action. Clarity protects both the money and the friendship.</p><div className="note-rule" /><small>2 open loops · ₹11,500 total</small></div></div></section>;
}
function SectionHeading({ eyebrow, title, action }) { return <div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><button className="outline-btn">{action}</button></div>; }

function App() {
  const [view, setView] = useState('overview');
  const [dashboard, setDashboard] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => { fetch(`${API}/dashboard`).then(r => r.ok ? r.json() : Promise.reject(new Error('Dashboard request failed'))).then(setDashboard).catch(() => setError('Backend is not running. Start Spring Boot on port 8080 to load live data.')); }, []);
  const demo = { stats: { focusedTime: '6h 10m', habits: '3 / 5', next30Days: '₹18,400', dayScore: 78 }, timeline: [{ time: '07:00', title: 'Morning routine', subtitle: 'Walk · breakfast · plan', status: 'done', type: 'wellbeing' }, { time: '09:30', title: 'Office hours', subtitle: 'Focus block · 09:30 — 18:30', status: 'active', type: 'work' }, { time: '19:30', title: 'DSA practice', subtitle: 'Arrays & hashing · 45 min', status: 'planned', type: 'learning' }, { time: '21:00', title: 'System design course', subtitle: 'Video 12 · consistency models', status: 'planned', type: 'course' }], courses: [{ name: 'DSA Patterns', progress: 42, completed: 50, total: 120, subtitle: '30-day sprint · 120 problems', color: 'dsa' }, { name: 'System Design / HLD', progress: 28, completed: 12, total: 42, subtitle: 'Architecture fundamentals', color: 'hld' }, { name: 'LLD with Java', progress: 16, completed: 8, total: 50, subtitle: 'Patterns · SOLID · practice', color: 'lld' }], loans: [{ name: 'Arjun Kapoor', initials: 'AK', amount: '₹8,000', dueDate: '12 Oct', status: 'Reminder soon', tone: 'warn', color: 'amber', note: 'Personal loan · sent 12 Sep 2026' }, { name: 'Neha Shah', initials: 'NS', amount: '₹3,500', dueDate: '28 Oct', status: 'On track', tone: 'quiet', color: 'pink', note: 'Travel split · sent 28 Sep 2026' }], finances: [{ name: 'Index fund SIP', date: '05 Oct', amount: '₹4,000', status: 'scheduled', tone: 'good' }, { name: 'Emergency fund SIP', date: '10 Oct', amount: '₹2,000', status: 'scheduled', tone: 'good' }, { name: 'Rent auto pay', date: '01 Oct', amount: '₹28,000', status: 'paid', tone: 'good' }, { name: 'Learning platform', date: '15 Oct', amount: '₹1,499', status: 'review', tone: 'warn' }, { name: 'Music subscription', date: '21 Oct', amount: '₹119', status: 'active', tone: 'quiet' }] };
  const data = dashboard || demo;
  return <div className="app-shell"><Sidebar view={view} setView={setView} /><main className="main"><Header setView={setView} />{error && <div className="backend-note">{error}</div>}{view === 'overview' ? <Overview dashboard={data} setView={setView} /> : <DetailView view={view} dashboard={data} setView={setView} />}</main></div>;
}

createRoot(document.getElementById('root')).render(<App />);
